name: cli
description: Tools, like an argument parser, to create command-line applications.
environment:
  sdk: ^2.0.0-alpha.144
dependencies:
  fs:
    url: github.com/toitlang/pkg-fs
    version: ^2.2.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.15.0
